name: Deploy Next.js to Azure

on:
  push:
    branches:
      - main
    paths:
      - "apps/nextjsv15/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      APP_PATH: apps/nextjsv15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js app
        run: pnpm --filter nextjsv15 build

      - name: Export Next.js app
        run: pnpm --filter nextjsv15 export

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List out directory
        run: ls -R ${{ env.APP_PATH }}/out

      - name: Debug Upload Command
        run: |
          echo "Running command:"
          echo "az storage blob upload-batch --auth-mode login --destination \"$web\" --account-name nextstaticstorage --source out --overwrite true"

      - name: Upload to Blob Storage
        working-directory: ${{ env.APP_PATH }}
        run: |
          az storage blob upload-batch \
            --auth-mode login \
            --destination "$web" \
            --account-name nextstaticstorage \
            --source out \
            --overwrite true
